# Generated by Django 3.2.16 on 2023-04-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_initial'),
        ('users', '0002_auto_20230402_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='cmsapp.department', verbose_name='Департамент'),
        ),
    ]
